# Generated by Django 5.1.7 on 2025-03-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.BigIntegerField()),
                ('test_reservation_date', models.DateField()),
                ('test_start_time', models.TimeField()),
                ('test_end_time', models.TimeField()),
                ('headcount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('AWAIT', '대기'), ('CONFIRM', '확정')], default='AWAIT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
