# Generated by Django 5.1.7 on 2025-03-25 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
